chore: Remove the custom logs from release build.
DiceTechnology/ExoPlayer pull request #54
Opened 2022-07-11 07:13 UTC by guoen21

2022-07-18 13:23 UTC, szaboa commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/DceLog.java
> +    return DEBUG_ENABLED && Log.getLogLevel() == Log.LOG_LEVEL_ALL;
Why do we need the `Log.getLogLevel() == Log.LOG_LEVEL_ALL` check? Can't we just have `DEBUG_ENABLED`? And call exo's `Log.d(...)` directly instead of `android.util.Log.d(...)`, like this: 
```
public static void d(@Size(max = 23) String tag, String message) {
    if (isDebugEnabled()) {
        Log.d(tag, message);
    }
  }
```

Similar for `isInfoEnabled` and `public static void i(...)`

2022-07-18 13:32 UTC, szaboa commented
I don't understand why do we need to check if log enabled before logging, the same condition is placed inside the log methods. So the wrapping logic should be enough.

Also I'd rename the `DceLog` to something else, `DorisLog`, or just `L`, what do you think?

2022-07-18 13:33 UTC, szaboa requested changes

2022-07-18 13:33 UTC, szaboa commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/DebugBase.java
> +        if (use_info && DceLog.isInfoEnabled()) {
Why do we need to check if `DceLog.isInfoEnabled()` ?  The check is inside `DceLog.i(...)`

2022-07-18 13:33 UTC, szaboa commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/DebugBase.java
> +        } else if (DceLog.isDebugEnabled()) {
Why do we need to check if `DceLog.isDebugEnabled()` ?  The check is inside `DceLog.d(...)`

2022-07-18 13:33 UTC, szaboa commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/TrackSwitcher.java
> +      if (DceLog.isDebugEnabled()) {
Why do we need to check if `DceLog.isDebugEnabled()` ?  The check is inside `DceLog.d(...)`

2022-07-18 13:33 UTC, szaboa commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/TrackSwitcher.java
> +      if (DceLog.isDebugEnabled()) {
Why do we need to check if `DceLog.isDebugEnabled()` ?  The check is inside `DceLog.d(...)`

2022-07-18 13:33 UTC, szaboa commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/WebUtil.java
> +        if (DceLog.isDebugEnabled()) {
same here

2022-07-18 13:33 UTC, szaboa commented on library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java
> +    if (!DebugUtil.debug_lowlatency || !DceLog.isDebugEnabled()) {
I don't see why do we need this extra check here.

2022-07-19 02:39 UTC, guoen21 commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/DceLog.java
> +    return DEBUG_ENABLED && Log.getLogLevel() == Log.LOG_LEVEL_ALL;
Modified.

2022-07-19 02:46 UTC, guoen21 commented on library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java
> +    if (!DebugUtil.debug_lowlatency || !DceLog.isDebugEnabled()) {
We use `isDebugEnabled()` to reduce the cost of building complex message string.

2022-07-19 02:46 UTC, guoen21 commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/WebUtil.java
> +        if (DceLog.isDebugEnabled()) {
Modified

2022-07-19 02:46 UTC, guoen21 commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/TrackSwitcher.java
> +      if (DceLog.isDebugEnabled()) {
Modified

2022-07-19 02:46 UTC, guoen21 commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/TrackSwitcher.java
> +      if (DceLog.isDebugEnabled()) {
Modified

2022-07-19 02:47 UTC, guoen21 commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/DebugBase.java
> +        } else if (DceLog.isDebugEnabled()) {
Modified

2022-07-19 02:47 UTC, guoen21 commented on library/common/src/main/java/com/google/android/exoplayer2/endeavor/DebugBase.java
> +        if (use_info && DceLog.isInfoEnabled()) {
Modified

2022-07-19 08:28 UTC, szaboa submitted a review, later dismissed

2022-07-19 09:27 UTC, szaboa approved these changes

2022-07-19 09:30 UTC, merged